---
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - { role: clickhouse }

- name: Install vector
  hosts: vector
  roles:
    - { role: vector-role }

- name: Install lighthouse
  hosts: lighthouse
  roles:
    - { role: lighthouse }