---
pre_tasks:
  - name: Apt update
    become: true
    ansible.builtin.apt:
      update_cache: true
  - name: Install git
    become: true
    ansible.builtin.apt:
      name: git
      state: present
  - name: Install nginx
    become: true
    ansible.builtin.apt:
      name: nginx
      state: present
  - name: Apply nginx config
    become: true
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      mode: '644'
tasks:
  - name: Clon Lighthouse repo
    ansible.builtin.git:
      repo: "https://github.com/VKCOM/lighthouse.git"
      dest: "/home/{{ ansible_user_id }}/lighthouse"
      version: master
post_tasks:
  - name: Apply lighthouse nginx config
    become: true
    ansible.builtin.template:
      src: lighthouse_nginx.conf.j2
      dest: /etc/nginx/conf.d/lighthouse.conf
      mode: '644'
    notify: Nginx reload
  