---
- name: Download Vector
  ansible.builtin.get_url:
    url: https://apt.vector.dev/pool/v/ve/vector_0.43.1-1_amd64.deb
    dest: /home/user/vector_0.43.1-1_amd64.deb
    mode: "0755"
- name: Install Vector
  become: true
  ansible.builtin.apt:
    deb: /home/user/vector_0.43.1-1_amd64.deb
- name: Updating vector config
  become: true
  ansible.builtin.template:
    src: templates/vector.j2
    dest: /etc/vector/vector.yaml
    mode: '644'
  notify: Restart vector
  